config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libercom.urls')),
    path('user/', include('users.urls')),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('', login_view, name='login'),
    path('home/', user_view, name='home'),
    path('logout/', logout_view, name='logout'),
    path('exit/', exit_view, name='exit'),

    path('quizz/', quizz_view, name='quizz'),

    path('statistics/', statistics_view, name='statistics'),
    path('char_data/', statistics_data, name='statistics_data'),


    path('testemunhos/', testemunho_view, name='testemunho'),
    path('testemunho-delete/<int:testemunho_id>', testemunho_delete_view, name='testemunho-delete'),
    path('testemunho-delete/confirmed/<int:testemunho_id>',
         testemunho_delete_confirmed_view, name='testemunho-delete-confirmed'),
    path('testemunho-edit/<int:testemunho_id>', testemunho_edit_view, name='testemunho-edit'),

    path('planos/', plano_view, name='planos'),
    path('planos/new/', plano_new_view, name='plano-new'),
    path('plano-edit/<int:plano_id>', plano_edit_view, name='plano-edit'),
    path('plano-delete/<int:plano_id>', plano_delete_view, name='plano-delete'),
    path('plano-delete/confirmed/<int:plano_id>', plano_delete_confirmed_view, name='plano-delete-confirmed'),


    path('users/', users_view, name='users'),
    path('users-delete/<int:contato_id>', users_delete_view, name='users-delete'),
    path('users-delete/confirmed/<int:contato_id>', users_delete_confirmed_view, name='users-delete-confirmed'),
    path('users-edit/<int:contato_id>', users_edit_view, name='users-edit'),
    path('users-new/', users_new_view, name='users-new'),
]

users/models.py
from django.db import models

users/views.py
import datetime

from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib import auth

# Create your views here.
from libercom.forms import *
from libercom.models import *
from users.utils import get_graphs


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request,
            username=username,
            password=password
        )

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:home'))
        else:
            return render(request, 'libercom/home.html', {
                'message': 'Credenciais inválidas.',
                'year': datetime.date.today().year,
            })

    return HttpResponseRedirect(reverse('libercom:home'))


def user_view(request):
    if request.user.is_authenticated:
        context = {'year': datetime.date.today().year, 'option': 1}
        return render(request, "users/index.html", context)

    return render(request, 'libercom/home.html', {
        'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
        'year': datetime.date.today().year,
    })


def logout_view(request):
    logout(request)
    auth.logout(request)
    return HttpResponseRedirect(reverse('libercom:home'))


def testemunho_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    context = {'form': Testemunho.objects.all(), 'year': datetime.date.today().year, 'option': 2}
    return render(request, 'users/testemunhos.html', context)


def testemunho_delete_view(request, testemunho_id):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    context = {'testemunho_id': testemunho_id, 'year': datetime.date.today().year, 'option': 2}
    return render(request, "users/testemunho_delete.html", context)


def testemunho_delete_confirmed_view(request, testemunho_id):
    Testemunho.objects.get(id=testemunho_id).delete()
    return HttpResponseRedirect(reverse('users:testemunho'))


def testemunho_edit_view(request, testemunho_id):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    testemunho = Testemunho.objects.get(id=testemunho_id)
    form = TestemunhoAdminForm(request.POST or None, instance=testemunho)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('users:testemunho'))

    context = {'form': form, 'testemunho_id': testemunho_id, 'year': datetime.date.today().year, 'option': 2}
    return render(request, "users/testemunho_edit.html", context)


def exit_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })
    return render(request, "users/exit.html", {'year': datetime.date.today().year})


def quizz_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })
    context = {'quizz': Quizz.objects.all(), 'year': datetime.date.today().year, 'option': 4}
    return render(request, 'users/quizz.html', context)


def statistics_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    context = {
        'contatos': len(Contato.objects.all()),
        'planos': len(Plano.objects.all()),
        'testemunho': len(Testemunho.objects.all()),
        'quizz': len(Quizz.objects.all()),
        'year': datetime.date.today().year,
        'option': 5,
    }
    return render(request, "users/statistics.html", context)


def statistics_data(request):
    graficos = get_graphs()

    # Return list of posts
    return JsonResponse(graficos)


def plano_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    context = {'planos': Plano.objects.all(), 'year': datetime.date.today().year, 'option': 6}
    return render(request, 'users/planos.html', context)


def plano_new_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    form = PlanoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('users:planos'))

    context = {'form': form, 'year': datetime.date.today().year, 'option': 6}
    return render(request, 'users/plano_new.html', context)


def plano_edit_view(request, plano_id):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    plano = Plano.objects.get(id=plano_id)
    form = PlanoForm(request.POST or None, instance=plano)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('users:planos'))

    context = {'form': form, 'plano_id': plano_id, 'year': datetime.date.today().year, 'option': 6}
    return render(request, "users/plano_edit.html", context)


def plano_delete_view(request, plano_id):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    context = {'year': datetime.date.today().year, 'plano': Plano.objects.get(pk=plano_id), 'option': 6}
    return render(request, 'users/plano-delete.html', context)


def plano_delete_confirmed_view(request, plano_id):
    Plano.objects.get(id=plano_id).delete()
    return HttpResponseRedirect(reverse('users:planos'))


def users_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    context = {'year': datetime.date.today().year, 'contatos': Contato.objects.all(), 'option': 3}
    return render(request, "users/users.html", context)


def users_delete_view(request, contato_id):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })
    context = {'year': datetime.date.today().year, 'contato': Contato.objects.get(pk=contato_id), 'option': 3}
    return render(request, 'users/users-delete.html', context)


def users_delete_confirmed_view(request, contato_id):
    Contato.objects.get(id=contato_id).delete()
    return HttpResponseRedirect(reverse('users:users'))


def users_edit_view(request, contato_id):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    contato = Contato.objects.get(id=contato_id)
    form = ContatoForm(request.POST or None, instance=contato)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('users:users'))

    context = {'form': form, 'contato_id': contato_id, 'year': datetime.date.today().year, 'option': 3}
    return render(request, "users/users-edit.html", context)


def users_new_view(request):
    if not request.user.is_authenticated:
        return render(request, 'libercom/home.html', {
            'message': 'Sem permissão para acessar esta página. Realize o login e tente novamente',
            'year': datetime.date.today().year,
        })

    form = ContatoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('users:users'))

    context = {'form': form, 'year': datetime.date.today().year, 'option': 3}
    return render(request, 'users/users-new.html', context)

users/templates/users/base.html
<!DOCTYPE html>
<html lang="pt">
    <head>
        {% load static %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Libercom - APP</title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'libercom/img/favicon.ico' %}"/>
        <link href="{% static 'users/lib/bootstrap-4.5.3-dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'users/lib/fontawesome/css/all.css' %}" />
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <link href="{% static 'users/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'users/css/forms.css' %}" rel="stylesheet">
        <link href="{% static 'users/css/other.css' %}" rel="stylesheet">
        <link href="{% static 'users/css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="biv-panel">
            <!-- Left panel  -->
            <div class="biv-left">
                <div class="biv-left-header">
                    <a href="{% url 'users:home' %}" class="biv-left-header-logo">
                        <img src="{% static 'users/img/logo.png' %}" alt="Company name">
                    </a>
                    <a href="{% url 'users:home' %}" class="biv-left-header-title">Painel de Controle</a>
                    <span onclick="BivNavBtn();">
                        <i class="fas fa-times"></i>
                    </span>
                </div>
                <div class="biv-left-nav">
                    <ul class="biv-header-nav-items">
                        <li id="menu1">
                            <a href="{% url 'users:home' %}"><span><i class="fas fa-book-open"></i></span>Home</a>
                        </li>
                        <li id="menu2">
                            <a href="{% url 'users:testemunho' %}"><span><i class="fas fa-envelope"></i></span>Testemunhos</a>
                        </li>
                        <li id="menu3">
                            <a href="{% url 'users:users' %}"><span><i class="fas fa-users"></i></span>Contatos</a>
                        </li>
                        <li id="menu4">
                            <a href="{% url 'users:quizz' %}"><span><i class="fas fa-search"></i></span>Quizz</a>
                        </li>
                        <li id="menu5">
                            <a href="{% url 'users:statistics' %}"><span><i class="fas fa-chart-pie"></i></span>Estatísticas</a>
                        </li>
                        <li id="menu6">
                            <a href="{% url 'users:planos' %}"><span><i class="fas fa-code"></i></span>Planos</a>
                        </li>
                    </ul>
                </div>
                <div class="biv-left-footer">© {{ year }} Libercom</div>
            </div>
            <!-- Left panel  -->
            <!-- User panel   -->
            <div class="biv-user">
                <div class="biv-user-menu">
                    <span onclick="BivNavBtn();">
                        <i class="fas fa-bars"></i>
                    </span>
                </div>
                <div class="biv-user-info">
                    <span class="biv-user-info-img biv-background" data-src="{% static 'users/img/demo/user/01.jpg' %}"></span>
                    <span class="biv-user-info-name">{{ user.first_name }} {{ user.last_name }}</span>
                </div>
                <div class="biv-user-nav">
                    <a href="{% url 'users:exit' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </div>
            </div>
            <!-- User panel   -->
            {% block main %}

            {% endblock %}
        </div>
        <script src="{% static 'users/js/scripts.js' %}"></script>
        <script>
            BivSection('{{ option }}');
        </script>
    </body>
</html>

users/templates/users/exit.html
{% extends 'users/base.html' %}

{% block main %}
<!-- Fast passage   -->
        <div class="biv-location">
            <span>Sair</span>
        </div>
<!-- Fast passage   -->

<!-- Content   -->
        <div class="biv-panel-content">

            <div class="biv-form">
                <div class="biv-form-title">Sair do painel de controle</div>
                <div class="biv-form-line"></div>
                <div class="biv-form-text">
                    <p>Deseja mesmo sair do Painel de Controle?</p>
                </div>
                <div class="biv-form-line"></div>
                <a href="{% url 'users:logout' %}" class="biv-form-btn-right">
                    <span>Sair</span>
                </a>
            </div>

        </div>
<!-- Content   -->
{% endblock %}

users/templates/users/index.html
{% extends 'users/base.html' %}

{% block main %}
    <!-- Fast passage   -->
    <div class="biv-location">
        <span>Home page</span>
    </div>
    <!-- Fast passage   -->

    <!-- Content   -->
    <div class="biv-panel-content">

        <div class="biv-panel-tiles">
            <div class="row">
                <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                    <a href="{% url 'users:testemunho' %}" class="biv-panel-tile">
                        <div class="biv-panel-tile-icon">
                            <i class="fas fa-envelope"></i>
                        </div>
                        <div class="biv-panel-tile-title">Testemunhos</div>
                    </a>
                </div>
                <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                    <a href="{% url 'users:users' %}" class="biv-panel-tile">
                        <div class="biv-panel-tile-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <div class="biv-panel-tile-title">Contatos</div>
                    </a>
                </div>
                <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                    <a href="{% url 'users:quizz' %}" class="biv-panel-tile">
                        <div class="biv-panel-tile-icon">
                            <i class="fas fa-question"></i>
                        </div>
                        <div class="biv-panel-tile-title">Quizz</div>
                    </a>
                </div>
                <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                    <a href="{% url 'users:planos' %}" class="biv-panel-tile">
                        <div class="biv-panel-tile-icon">
                            <i class="fas fa-wifi"></i>
                        </div>
                        <div class="biv-panel-tile-title">Planos</div>
                    </a>
                </div>
                <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                    <a href="{% url 'users:statistics' %}" class="biv-panel-tile">
                        <div class="biv-panel-tile-icon">
                            <i class="far fa-chart-bar"></i>
                        </div>
                        <div class="biv-panel-tile-title">Estatísticas</div>
                    </a>
                </div>
            </div>
        </div>


    </div>
    <!-- Content   -->
{% endblock %}

users/templates/users/plano-delete.html
{% extends 'users/base.html' %}

{% block main %}
<!-- Fast passage   -->
        <div class="biv-location">
            <a href="{% url  'users:planos' %}">Planos</a>
            <span>Deletar Plano</span>
        </div>
<!-- Fast passage   -->

<!-- Content   -->
        <div class="biv-panel-content">

            <div class="biv-form">
                <div class="biv-form-title">Deletar plano de {{ plano.name }}</div>
                <div class="biv-form-line"></div>
                <div class="biv-form-text">
                    <p>O plano será deletado da sua base de dados.</p>
                </div>
                <div class="biv-form-line"></div>
                <div class="biv-form-btn-right">
                    <a href="{% url  'users:plano-delete-confirmed' plano.id %}">Delete</a>
                </div>
            </div>
        </div>
<!-- Content   -->
{% endblock %}

users/templates/users/planos.html
{% extends 'users/base.html' %}

{% block main %}
<!-- Fast passage   -->
        <div class="biv-location">
            <span>Planos</span>
        </div>
<!-- Fast passage   -->

<!-- Content   -->
        <div class="biv-panel-content">

            <div class="biv-panel-btns">
                <a href="{% url  'users:plano-new' %}" class="biv-panel-btn">Adicionar Plano</a>
            </div>

            <div class="biv-panel-tiles">
                <div class="row">
                    {% for plano in planos %}
                        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                            <a href="{% url  'users:plano-edit' plano.id %}" class="biv-panel-tile">
                                <div class="biv-panel-tile-icon">
                                    <i class="{{ plano.icon }}"></i>
                                </div>
                                <div class="biv-panel-tile-title">{{ plano.name }} MEGAS</div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
<!-- Content   -->
{% endblock %}

users/templates/users/quizz.html
{% extends 'users/base.html' %}

{% block main %}
<!-- Fast passage   -->
        <div class="biv-location">
            <span>Quizz</span>
        </div>
<!-- Fast passage   -->

<!-- Content   -->
<!-- Content   -->
        <div class="biv-panel-content">
            <div class="biv-panel-stat">
                <div class="row">
                    {% for q in quizz %}
                        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                            <div class="biv-panel-stat-item">
                                <div class="biv-panel-stat-item-count">{{ q.nota }}</div>
                                <div class="biv-panel-stat-item-title">{{ q.name }}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
<!-- Content   -->
{% endblock %}

users/templates/users/statistics.html
{% extends 'users/base.html' %}

{% block main %}
<!-- Fast passage   -->
        <div class="biv-location">
            <span>Estatísticas</span>
        </div>
<!-- Fast passage   -->

<!-- Content   -->
        <div class="biv-panel-content">

            <div class="biv-panel-stat">
                <div class="row">
                    <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                        <div class="biv-panel-stat-item">
                            <div class="biv-panel-stat-item-count">{{ contatos }}</div>
                            <div class="biv-panel-stat-item-title">Contatos</div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                        <div class="biv-panel-stat-item">
                            <div class="biv-panel-stat-item-count">{{ testemunho }}</div>
                            <div class="biv-panel-stat-item-title">Testemunhos</div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                        <div class="biv-panel-stat-item">
                            <div class="biv-panel-stat-item-count">{{ quizz }}</div>
                            <div class="biv-panel-stat-item-title">Quizzes</div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                        <div class="biv-panel-stat-item">
                            <div class="biv-panel-stat-item-count">{{ planos }}</div>
                            <div class="biv-panel-stat-item-title">Planos</div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="chart" class="container"></div>
        </div>
<!-- Content   -->

    <script>
        function make_statement(data){
            var str = "["
            data.forEach(d =>
                str += "'" + d + "',"
            )
            str = str.substring(0, str.length - 1);
            str += "],"
            return str;
        }

        function make_url(data_x,data_y,width ,height,str) {
            return "https://quickchart.io/chart?chart={" +
                "type: 'bar'," +
                "data: {" +
                    "labels:" + make_statement(data_x) +
                    "datasets: [{" +
                            "label: '"+ str +"'," +
                            "data:[" + data_y + "]" +
                        "}]" +
                    "}" +
                "}" +
                "&width=" + width +
                "&height=" + height +
                "&devicePixelRatio=1.0" +
                "&format=png" +
                "&version=2.9.3";
        }

        function  put_chart(url){
            fetch(url)
            .then(img => {
                //console.log(img.url);
                var tag = document.createElement("img");

                tag.src = img.url;
                var src = document.querySelector('#chart');

                src.appendChild(tag);
            })
        }

        fetch('{% url 'users:statistics_data' %}')
        .then(response => response.text() )
        .then(data => {
            var json = JSON.parse(data);

            //grafico geral
            var url = make_url(json.geral.x,json.geral.y,"900","300", "Perguntas vs Respostas Certas");
            put_chart(encodeURI(url));

            var pergunta;
            for (var i=1; i<11; i++){
                pergunta = json[("p"+ i.toString())]
                url = make_url(pergunta["x"],pergunta["y"],"420","300",("Pergunta "+ i.toString()));
                put_chart(encodeURI(url));
            }
        });

    </script>
{% endblock %}

users/templates/users/testemunho_delete.html
{% extends 'users/base.html' %}

{% block main %}
    <!-- Fast passage   -->
    <div class="biv-location">
        <a href="{% url 'users:testemunho' %}">Testemunho</a>
        <span>Deletar Testemunho</span>
    </div>
    <!-- Fast passage   -->
    
    <!-- Content   -->
    <div class="biv-panel-content">
    
        <div class="biv-form">
            <div class="biv-form-title">Deletar Testemunho</div>
            <div class="biv-form-line"></div>
            <div class="biv-form-text">
                <p>O testemunho será removido da base de dados.</p>
            </div>
            <div class="biv-form-line"></div>
            <div class="biv-form-btn-right">
                <a href="{% url 'users:testemunho-delete-confirmed' testemunho_id %}">Deletar</a>
            </div>
        </div>
    
    </div>
    <!-- Content   -->
{% endblock %}

users/templates/users/testemunhos.html
{% extends 'users/base.html' %}

{% block main %}
    <!-- Fast passage   -->
    <div class="biv-location">
        <span>Testemunhos</span>
    </div>
    <!-- Fast passage   -->
    
    <!-- Content   -->
    <div class="biv-panel-content">

            <div class="biv-panel-table">
                <div class="biv-panel-table-content">
                    <div class="biv-panel-table-title">Testemunhos</div>

                    <form method="POST" action="">
                        {% csrf_token %}
                        {% for testemunho in form %}
                            <div class="biv-panel-table-item">
                                <div class="biv-panel-table-item-title">
                                    {{ testemunho.name }} {{ testemunho.apelido }}<br>
                                    {% if testemunho.voto == 1 %}
                                        <span >⭐</span><br><br>
                                    {% elif testemunho.voto == 2 %}
                                        <span >⭐⭐</span><br><br>
                                    {% elif testemunho.voto == 3 %}
                                        <span >⭐⭐⭐</span><br><br>
                                    {% elif testemunho.voto == 4 %}
                                        <span >⭐⭐⭐⭐</span><br><br>
                                    {% elif testemunho.voto == 5 %}
                                        <span >⭐⭐⭐⭐⭐</span><br><br>
                                    {% endif %}
                                    {{ testemunho.testemunho }}</div>
                                <div class="biv-panel-table-item-settings">
                                    <a href="{% url 'users:testemunho-edit' testemunho.id %}">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    <a href="{% url 'users:testemunho-delete' testemunho.id %}">
                                        <i class="fas fa-times"></i>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
        <!-- Content   -->
{% endblock %}

users/templates/users/users-delete.html
{% extends 'users/base.html' %}

{% block main %}
<!-- Fast passage   -->
        <div class="biv-location">
            <a href="{% url  'users:users' %}">Contatos</a>
            <span>Deletar Contato</span>
        </div>
<!-- Fast passage   -->

<!-- Content   -->
        <div class="biv-panel-content">

            <div class="biv-form">
                <div class="biv-form-title">Deletar Contato: {{ contato.name }}</div>
                <div class="biv-form-line"></div>
                <div class="biv-form-text">
                    <p>O usuario será deletado da sua base de dados.</p>
                </div>
                <div class="biv-form-line"></div>
                <div class="biv-form-btn-right">
                    <a href="{% url  'users:users-delete-confirmed' contato.id %}">Delete</a>
                </div>
            </div>
        </div>
<!-- Content   -->
{% endblock %}

users/templates/users/users.html
{% extends 'users/base.html' %}

{% block main %}
<!-- Fast passage   -->
        <div class="biv-location">
            <span>Contatos</span>
        </div>
<!-- Fast passage   -->

<!-- Content   -->
        <div class="biv-panel-content">

            <div class="biv-panel-btns">
                <a href="{% url  'users:users-new' %}" class="biv-panel-btn">Adicionar Contato</a>
            </div>

            <div class="biv-panel-table">
                <div class="biv-panel-table-content">
                    <div class="biv-panel-table-title">Lista de Usuários</div>
                    {% for contato in contatos %}
                        <div class="biv-panel-table-item">
                            <div class="biv-panel-table-item-title">{{ contato.name }}</div>
                            <div class="biv-panel-table-item-settings">
                                <a href="{% url  'users:users-edit' contato.id %}">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>
                                <a href="{% url  'users:users-delete' contato.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

        </div>
<!-- Content   -->
{% endblock %}