config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libercom.urls')),
    path('user/', include('users.urls')),
]

libercom/urls.py
from django.urls import path

from . import views

app_name = 'libercom'

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('plano/', views.plano_view, name='plano'),
    path('quizz/', views.quizz_view, name='quizz'),
    path('sobre/', views.sobre_view, name='sobre'),
    path('contato/', views.add_page_view, name="adicionar"),
    path('success/', views.success_view, name="success"),
    path('sitemap/', views.sitemap_view, name="sitemap"),
    path('add/testemunho/', views.add_testemunho_view, name="add-testemunho"),
    path('add/testemunho/success', views.add_testemunho_success_view, name="add-testemunho-success")
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('', login_view, name='login'),
    path('home/', user_view, name='home'),
    path('logout/', logout_view, name='logout'),
    path('exit/', exit_view, name='exit'),

    path('quizz/', quizz_view, name='quizz'),

    path('statistics/', statistics_view, name='statistics'),
    path('char_data/', statistics_data, name='statistics_data'),


    path('testemunhos/', testemunho_view, name='testemunho'),
    path('testemunho-delete/<int:testemunho_id>', testemunho_delete_view, name='testemunho-delete'),
    path('testemunho-delete/confirmed/<int:testemunho_id>',
         testemunho_delete_confirmed_view, name='testemunho-delete-confirmed'),
    path('testemunho-edit/<int:testemunho_id>', testemunho_edit_view, name='testemunho-edit'),

    path('planos/', plano_view, name='planos'),
    path('planos/new/', plano_new_view, name='plano-new'),
    path('plano-edit/<int:plano_id>', plano_edit_view, name='plano-edit'),
    path('plano-delete/<int:plano_id>', plano_delete_view, name='plano-delete'),
    path('plano-delete/confirmed/<int:plano_id>', plano_delete_confirmed_view, name='plano-delete-confirmed'),


    path('users/', users_view, name='users'),
    path('users-delete/<int:contato_id>', users_delete_view, name='users-delete'),
    path('users-delete/confirmed/<int:contato_id>', users_delete_confirmed_view, name='users-delete-confirmed'),
    path('users-edit/<int:contato_id>', users_edit_view, name='users-edit'),
    path('users-new/', users_new_view, name='users-new'),
]

libercom/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Plano(models.Model):
    name = models.CharField(verbose_name="Nome", max_length=20)
    index = models.IntegerField()
    upload = models.CharField(max_length=20, null=True)
    download = models.CharField(max_length=20, null=True)
    roteador = models.CharField(max_length=50, null=True, blank=True)
    price = models.CharField(verbose_name="Preço", max_length=15, null=True, blank=True)
    icon = models.CharField(verbose_name="Icone", max_length=50, null=True, blank=True)
    destaque = models.BooleanField(verbose_name="Destaque", default=False)
    image_name = models.CharField(verbose_name="Nome do arquivo", max_length=40, blank=True)

    def __str__(self):
        return f"{self.name} MEEGAS= R${self.price},00"


class Contato(models.Model):
    name = models.CharField(verbose_name="Nome", max_length=200)
    birth = models.DateField(verbose_name="Data de Nascimento", null=True, blank=True)
    phone = models.CharField(verbose_name="Telemóvel", max_length=21)
    email = models.EmailField(verbose_name="E-mail", max_length=254)
    plano = models.ForeignKey(Plano, on_delete=models.CASCADE, verbose_name="Plano", related_name="planos")

    def __str__(self):
        return self.name[:200]


class Testemunho(models.Model):
    ESTRELAS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    name = models.CharField(verbose_name="Name", max_length=30)
    apelido = models.CharField(verbose_name="Apelido", max_length=30)
    testemunho = models.TextField(verbose_name="Testemunho", max_length=350)
    enable = models.BooleanField(verbose_name="Visivel", default=True)
    voto = models.IntegerField(verbose_name="Voto", choices=ESTRELAS)

    def __str__(self):
        return f'{self.name} {self.apelido}'


class Quizz(models.Model):
    name = models.CharField(verbose_name="Nome", max_length=200, blank=True)
    p1 = models.IntegerField(verbose_name="p1", blank=True)
    p2 = models.IntegerField(verbose_name="p2", blank=True)
    p3 = models.IntegerField(verbose_name="p3", blank=True)
    p4 = models.IntegerField(verbose_name="p4", blank=True)
    p5 = models.IntegerField(verbose_name="p5", blank=True)
    p6 = models.IntegerField(verbose_name="p6", blank=True)
    p7 = models.IntegerField(verbose_name="p7", blank=True)
    p8 = models.IntegerField(verbose_name="p8", blank=True)
    p9 = models.IntegerField(verbose_name="p9", blank=True)
    p10 = models.IntegerField(verbose_name="p10", blank=True)
    nota = models.IntegerField(verbose_name="Nota", blank=True)

    def __str__(self):
        return self.name


class Newsletter(models.Model):
    name = models.CharField(verbose_name="Nome", max_length=200)
    email = models.EmailField(verbose_name="E-mail", max_length=254)

    def __str__(self):
        return self.name
# class Testimony(models.Model):
#     VOTO_CHOICES = (
#         (1, "1"),
#         (2, "2"),
#         (3, "3"),
#         (4, "4"),
#         (5, "5")
#     )
#
#     anonimo = models.BooleanField()
#     testimony = models.TextField(max_length=255)
#     voto = models.IntegerField(choices=VOTO_CHOICES)
#
#
# class Profile(models.Model):
#     first_name = models.CharField(verbose_name="Primeiro Nome", max_length=40)
#     last_name = models.CharField(verbose_name="Último Nome", max_length=40)
#     user = models.CharField(verbose_name="Nome do usuário", max_length=40)
#     password = models.CharField(verbose_name="Senha", max_length=25)
#     phone = models.CharField(verbose_name="Telemóvel", max_length=21)
#     email = models.EmailField(verbose_name="E-mail", max_length=254)
#     birth_date = models.DateField(verbose_name="Data de Nascimento", null=True, blank=True)
#     is_admin = models.BooleanField()
#
#     class Meta:
#         abstract = True
#
#
# class Subscriber(Profile):
#     plano = models.ForeignKey(Plano, on_delete=models.CASCADE, verbose_name="Plano", related_name="plano")
#     testimony = models.ForeignKey(Testimony, on_delete=models.CASCADE, blank=True, null=True,)
#     quizz = models.ForeignKey(Quizz, on_delete=models.CASCADE, blank=True, null=True,)
#
#     def __str__(self):
#         return f"{self.first_name} {self.last_name}"

libercom/forms.py
from django import forms
from django.forms import ModelForm, NumberInput
from .models import *


class ContatoForm(ModelForm):
    class Meta:
        model = Contato
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': "form-control"}),
            'birth': NumberInput(attrs={'type': 'date', 'class': "form-control"}),
            'phone': forms.TextInput(attrs={'class': "form-control"}),
            'email': forms.TextInput(attrs={'class': "form-control"}),
            'plano': forms.Select(attrs={'class': "form-control"}),
        }


class PlanoForm(ModelForm):
    class Meta:
        model = Plano
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': "form-control"}),
            'index': NumberInput(attrs={'class': "form-control"}),
            'upload': forms.TextInput(attrs={'class': "form-control"}),
            'download': forms.TextInput(attrs={'class': "form-control"}),
            'roteador': forms.TextInput(attrs={'class': "form-control"}),
            'price': forms.TextInput(attrs={'class': "form-control"}),
            'icon': forms.TextInput(attrs={'class': "form-control"}),
            'image_name': forms.TextInput(attrs={'class': "form-control"}),
        }


class TestemunhoForm(ModelForm):
    class Meta:
        model = Testemunho
        fields = 'name', 'apelido', 'testemunho', 'voto'
        widgets = {
            'name': forms.TextInput(),
            'apelido': forms.TextInput(),
            'testemunho': forms.Textarea(attrs={'id': "text_area"}),
            'voto': forms.Select(choices=Testemunho.ESTRELAS, attrs={'class': "form-control"}),
        }


class TestemunhoAdminForm(ModelForm):
    class Meta:
        model = Testemunho
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': "form-control"}),
            'apelido': forms.TextInput(attrs={'class': "form-control"}),
            'testemunho': forms.Textarea(attrs={'class': "form-control"}),
            'voto': forms.Select(choices=Testemunho.ESTRELAS, attrs={'class': "form-control"}),
        }

libercom/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
import datetime

from django.urls import reverse

from .models import *
from .forms import ContatoForm, TestemunhoForm


# Create your views here.
def home_page_view(request):
    context = {
        'year': datetime.date.today().year,
        'testemunho': Testemunho.objects.all(),
        'planos': Plano.objects.all().order_by('index'),
    }
    return render(request, 'libercom/home.html', context)


def add_page_view(request):
    form = ContatoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('libercom:success'))

    context = {'form': form, 'year': datetime.date.today().year}
    return render(request, 'libercom/add.html', context)


def success_view(request):
    context = {'year': datetime.date.today().year}
    return render(request, 'libercom/success.html', context)


def quizz_view(request):
    if request.method == "POST":
        name = request.POST['name']
        p1 = int(request.POST['p1'])
        p2 = int(request.POST['p2'])
        p3 = int(request.POST['p3'])
        p4 = int(request.POST['p4'])
        p5 = int(request.POST['p5'])
        p6 = int(request.POST['p6'])
        p7 = int(request.POST['p7'])
        p8 = int(request.POST['p8'])
        p9 = int(request.POST['p9'])
        p10 = int(request.POST['p10'])

        nota = 0

        if p1 == 1:
            nota += 10

        if p2 == 4:
            nota += 10

        if p3 == 1:
            nota += 10

        if p4 == 4:
            nota += 10

        if p5 == 1:
            nota += 10

        if p6 == 2:
            nota += 10

        if p7 == 1:
            nota += 10

        if p8 == 1:
            nota += 10

        if p9 == 1:
            nota += 10

        if p10 == 1:
            nota += 10

        q = Quizz(
            name=name,
            p1=p1, p2=p2, p3=p3, p4=p4, p5=p5,
            p6=p6, p7=p7, p8=p8, p9=p9, p10=p10,
            nota=nota
        )
        q.save()

        context = {'name': name, 'nota': nota, 'year': datetime.date.today().year}
        return render(request, 'libercom/nota.html', context)

    context = {'year': datetime.date.today().year}
    return render(request, 'libercom/quizz.html', context)


def plano_view(request):
    context = {
        'year': datetime.date.today().year,
        'planos': Plano.objects.all().order_by('index'),
    }
    return render(request, 'libercom/pricing.html', context)


def sobre_view(request):
    context = {'year': datetime.date.today().year, 'testemunho': Testemunho.objects.all()}
    return render(request, 'libercom/about.html', context)


def sitemap_view(request):
    context = {'year': datetime.date.today().year}
    return render(request, 'libercom/sitemap.html', context)


def add_testemunho_view(request):
    form = TestemunhoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('libercom:add-testemunho-success'))

    context = {'form': form, 'year': datetime.date.today().year}
    return render(request, 'libercom/testemunho_add.html', context)


def add_testemunho_success_view(request):
    return render(request, 'libercom/success_testemunho.html', {'year': datetime.date.today().year})

libercom/templates/libercom/add.html
{% extends "libercom/base.html" %}

{% block main %}
    <div class="container" id="add_div">
        <div class="container" id="add_div">
            <h3 id="title_add">Adiconar um Contato</h3>
            <form  id="form_add" method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}

                <input id="submit" type="submit" value="+ Adicionar">
            </form>
        </div>
    </div>

{% endblock %}

libercom/templates/libercom/nota.html
{% extends "libercom/base.html" %}

{% block main %}
    <div class="container" id="success_div">
        <h3 class="success_title">{{ name }} sua nota do Quizz foi {{ nota }}/100</h3>
        {% if nota <= 40 %}
            <p>Acho que podemos melhorar essa nota. Tente fazer o teste novamente</p>
            <a class="home_button" href="{% url 'libercom:quizz' %}">Tentar Novamente</a>
        {% elif nota <= 70 %}
            <p>Você foi muito bem, mas acho que pode ser ainda melhor. Tente fazer o teste novamente</p>
            <a class="home_button" href="{% url 'libercom:quizz' %}">Tentar Novamente</a>
        {% elif nota <= 95 %}
            <p>Parabéns pela excelente nota!! Por pouco não acertou todas em. Será que consegue acertar 100%? </p>
            <a class="home_button" href="{% url 'libercom:quizz' %}">Tentar Novamente</a>
        {% elif nota == 100 %}
            <p>Temos um verdadeiro profissional aqui. Isso não representou desafio para você pelo visto.
            Deixe seu contato conosco para quando tivermos um quizz mais difícil te notificarmos pelo e-mail.</p>
            <a class="home_button" href="{% url 'libercom:adicionar' %}">Adicionar Contato</a>
        {% endif %}
    </div>
{% endblock %}

libercom/templates/libercom/pricing.html
{% extends "libercom/base.html" %}

{% block main %}
    <!-- Start of page breadcrum
     ============================================= -->
    <section id="apus-breadscrumb" class="apus-breadscrumb">
     <div class="container">
        <div class="row">
           <div class="wrapper-breads">
              <div class="breadscrumb-inner">
                 <ol class="breadcrumb">
                    <li><a href="{% url 'libercom:home' %}">Home</a>  </li>
                    <li class="active">Planos</li>
                 </ol>
                 <h2 class="bread-title">Planos</h2>
              </div>
           </div>
        </div>
     </div>
    </section>
    <!-- End of page breadcrum
     ============================================= -->
    <!-- Start of pricing table
    ============================================= -->
    <section id="pricing-2" class="pricing-2-section">
        <div class="container">
                <div class="pricing-plan-content">
                        {% for plano in planos %}
                            {% if plano.index == 1 or plano.index == 4 %}
                                <div class="row">
                            {% endif %}
                            {% if plano.destaque %}
                                <div class="col-sm-4">
                                    <div class="kc-elm kc-css-835772 kc-pricing-tables kc-pricing-layout-2 colmd4 text-center mddl">
                                        <div class="priceing-label">
                                            MAIS VENDIDO
                                        </div>
                            {% else %}
                                <div class="col-sm-4">
                                    <div class="kc-elm kc-css-835772 kc-pricing-tables kc-pricing-layout-2 colmd4 text-center">
                            {% endif %}
                                        <div class="header-pricing">
                                            <div class="content-title">
                                                <div id="plano_name">{{ plano.name }}</div>
                                                <div class="content-sub-title">MEGAS</div>
                                            </div>
                                              <div class="kc-pricing-price">
                                                 <span class="content-currency">R$</span>
                                                 <span class="content-price">{{ plano.price }}</span>
                                                 <span class="content-duration">/mês</span>
                                              </div>
                                            </div>
                                        <ul class="content-desc">
                                            <li>{{ plano.roteador }}</li>
                                            <li>{{ plano.download }} de download</li>
                                            <li>{{ plano.upload }} de upload</li>
                                        </ul>
                                        <div class="content-button text-uppercase"><a href="#">Assine Já</a></div>
                                    </div>
                                </div>
                            {% if plano.index == 3 or plano.index == 6 %}
                                </div>
                            {% endif %}
                        {% endfor %}

                </div>
            </div>
        </div>
        </div>
    </section>
    <!-- End of pricing table
    ============================================= -->
{% endblock %}

libercom/templates/libercom/quizz.html
{%  extends "libercom/base.html" %}

{% block main %}
    <!-- Start of page breadcrum
     ============================================= -->
    <section id="apus-breadscrumb" class="apus-breadscrumb">
     <div class="container">
        <div class="row">
           <div class="wrapper-breads">
              <div class="breadscrumb-inner">
                 <ol class="breadcrumb">
                    <li><a href="{% url 'libercom:home' %}">Home</a>  </li>
                    <li class="active">Quizz</li>
                 </ol>
                 <h2 class="bread-title">Quizz</h2>
              </div>
           </div>
        </div>
     </div>
    </section>
    <!-- End of page breadcrum
     ============================================= -->
     <section class="container" id="add_div" >

        <form id="form_add" method="POST" action="{% url 'libercom:quizz' %}">
            {% csrf_token %}
            <label for="1">Nome Completo
                <input type="text" name="name" value="">
            </label><br>

            <fieldset>
                <legend style="align-self: center">Teste suas habilidades</legend>

                <p>1- Qual o significado de www?</p>
                <input type="radio" id="1" name="p1" value="1">
                <label for="1">world wide web</label><br>
                <input type="radio" id="2" name="p1" value="2">
                <label for="2">wide world web</label><br>
                <input type="radio" id="3" name="p1" value="3">
                <label for="3">when wide web</label><br>
                <input type="radio" id="4" name="p1" value="4">
                <label for="4">what wide web</label>
                <br><br>

                <p>2- Quem criou o telégrafo?</p>
                <input type="radio" id="5" name="p2" value="1">
                <label for="5">Júlio Cezar</label><br>
                <input type="radio" id="6" name="p2" value="2">
                <label for="6">Abraham Lincoln</label><br>
                <input type="radio" id="7" name="p2" value="3">
                <label for="7">Thomas Edison</label><br>
                <input type="radio" id="8" name="p2" value="4">
                <label for="8">Samuel Morse</label>
                <br><br>

                <p>3- O primeiro protótipo de telefone foi criado por?</p>
                <input type="radio" id="9" name="p3" value="1">
                <label for="9">Graham Bell</label><br>
                <input type="radio" id="10" name="p3" value="2">
                <label for="10">Guglielmo Marconi</label><br>
                <input type="radio" id="11" name="p3" value="3">
                <label for="11">Landell de Moura</label><br>
                <input type="radio" id="12" name="p3" value="4">
                <label for="12">Antonio Meucci</label>
                <br><br>

                <p>4- Quem foi o inventor do rádio?</p>
                <input type="radio" id="13" name="p4" value="1">
                <label for="13">Gilberto Gil</label><br>
                <input type="radio" id="14" name="p4" value="2">
                <label for="14">Johann-Philipp</label><br>
                <input type="radio" id="15" name="p4" value="3">
                <label for="15">Ventura</label><br>
                <input type="radio" id="16" name="p4" value="4">
                <label for="16">Antonio Meucci</label>
                <br><br>

                <p>5- O que significa GPS?</p>
                <input type="radio" id="17" name="p5" value="1">
                <label for="17">global positioning system</label><br>
                <input type="radio" id="18" name="p5" value="2">
                <label for="18">geral positioning system</label><br>
                <input type="radio" id="19" name="p5" value="3">
                <label for="19">general positioning system</label><br>
                <input type="radio" id="20" name="p5" value="4">
                <label for="20">universal positioning system. </label>
                <br><br>

                <p>6- Qual opção esta correcta?</p>
                <input type="radio" id="21" name="p6" value="1">
                <label for="21">Thomas Edison foi o inventor da televisão</label><br>
                <input type="radio" id="22" name="p6" value="2">
                <label for="22">As antenas de telecomunicações atuam como transmissores de sinal</label><br>
                <input type="radio" id="23" name="p6" value="3">
                <label for="23">O palmeiras não tem mundial</label><br>
                <input type="radio" id="24" name="p6" value="4">
                <label for="24">O sistema android é um produto da Apple</label>
                <br><br>

                <p>7- A televisão no Brasil surgiu em?</p>
                <input type="radio" id="25" name="p7" value="1">
                <label for="25">1965</label><br>
                <input type="radio" id="26" name="p7" value="2">
                <label for="26">2000</label><br>
                <input type="radio" id="27" name="p7" value="3">
                <label for="27">1800</label><br>
                <input type="radio" id="28" name="p7" value="4">
                <label for="28">1970</label>
                <br><br>

                <p>8- Qual opção esta correcta?</p>
                <input type="radio" id="29" name="p8" value="1">
                <label for="29">A internet surgiu a partir de pesquisas militares no auge da Guerra Fria.</label><br>
                <input type="radio" id="30" name="p8" value="2">
                <label for="30">O primeiro protótipo da primeira rede de internet foi a Intra</label><br>
                <input type="radio" id="31" name="p8" value="3">
                <label for="31">O Wi-fi foi inventado pelos japoneses</label><br>
                <input type="radio" id="31" name="p8" value="4">
                <label for="32">O primeiro computador foi inventado pelos Alemães</label>
                <br><br>

                <p>9- O que é cabo coaxial?</p>
                <input type="radio" id="32" name="p9" value="1">
                <label for="32">Uma espécie de cabo condutor usado para a transmissão de sinais</label><br>
                <input type="radio" id="33" name="p9" value="2">
                <label for="33">Cabo utilizado para acabamentos em casas de banho</label><br>
                <input type="radio" id="34" name="p9" value="3">
                <label for="34">É utilizado para fins de mecânica industrial</label><br>
                <input type="radio" id="35" name="p9" value="4">
                <label for="35">É uma espécie de cabo resistente ao calor utilizado em grandes obras</label>
                <br><br>

                <p>10- O que significa IP?</p>
                <input type="radio" id="36" name="p10" value="1">
                <label for="36">Internet Protocol</label><br>
                <input type="radio" id="37" name="p10" value="2">
                <label for="37">Internet Process</label><br>
                <input type="radio" id="38" name="p10" value="3">
                <label for="38">Interface Protocol</label><br>
                <input type="radio" id="39" name="p10" value="4">
                <label for="39">Internet Program</label>
                <br><br>

                <input type="submit" value=" submter">
            </fieldset>
        </form>
     </section>
{% endblock %}

libercom/templates/libercom/register.html
{% extends "libercom/base.html" %}

{% block main %}
    <div class="container" id="add_div">
        <div class="container" id="add_div">
            <h3 id="title_add">Ficha de Cadastro</h3>
            <form  id="form_add" method="POST" action="">
                {% csrf_token %}
                <p>
                    <label for="id_first_name">Primeiro Nome:</label>
                    <input type="text" name="first_name" maxlength="40" required=""></p>
                <p>
                    <label for="id_last_name">Último Nome:</label>
                    <input type="text" name="last_name" maxlength="40" required=""></p>
                <p>
                    <label for="id_birth_date">Data de Nascimento:</label>
                    <input type="date" name="birth_date"></p>
                <p>
                    <label for="id_phone">Telemóvel:</label>
                    <input type="text" name="phone" maxlength="21" required=""></p>
                <p>
                    <label for="id_email">E-mail:</label>
                    <input type="email" name="email" maxlength="254" required=""></p>
                <p>
                    <label for="id_plano">Plano:</label>
                    <select name="plano" required="" id="id_plano">
                        <option value="">---------</option>
                        {% for plano in planos %}
                            <option value="{{ plano.id }}">{{ plano.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p>
                    <label for="id_user">Nome do usuário:</label>
                    <input type="text" name="username" maxlength="40" required=""></p>
                <p>
                    <label for="id_password">Senha:</label>
                    <input type="password" name="password" maxlength="25" required=""></p>

                <input id="submit" type="submit" value="+ Adicionar">
            </form>
        </div>
    </div>
{% endblock %}

libercom/templates/libercom/sitemap.html
{% extends "libercom/base.html" %}

{% block main %}
    {% load static %}
    <!-- Start of partner slide
    ============================================= -->
    <div id="partner-slide" class="partner-slide-section">
        <div class="container">
            <img src="{% static 'libercom/img/sitemap.png' %}" alt="mapa do site">
        </div>
    </div>
    <!-- End of partner slide
    ============================================= -->
{% endblock %}

libercom/templates/libercom/success.html
{% extends "libercom/base.html" %}

{% block main %}
    <div class="container" id="success_div">
        <h3 class="success_title">Contato adicionado com sucesso</h3>
        <p>Obrigado por adicionar o seu contato.</p>
        <a class="home_button" href="{% url 'libercom:home' %}">Home Page</a>
    </div>

{% endblock %}

libercom/templates/libercom/success_testemunho.html
{% extends "libercom/base.html" %}

{% block main %}
    <div class="container" id="success_div">
        <h3 class="success_title">Testemunho adicionado com sucesso</h3>
        <p>Obrigado por adicionar o seu testemunho. Sua opnião é muito importante para nós</p>
        <a class="home_button" href="{% url 'libercom:home' %}">Home</a>
    </div>

{% endblock %}

libercom/templates/libercom/testemunho_add.html
{% extends "libercom/base.html" %}

{% block main %}
    <div class="container" id="add_div">
        <div class="container" id="add_div">
            <h3 id="title_add">Adiconar um Contato</h3>
            <form  id="form_add" method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}

                <input id="submit" type="submit" value="+ Adicionar">
            </form>
        </div>
    </div>

{% endblock %}